version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379"
    restart: always

  web:
    build: .
    ports:
      - "3000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    hostname: short-url-web
    restart: always
    
networks:
  default:
    external:
      name: myNetwork

volumes:
  dbdata:

